### ISSUE TITLE
`npx executable-metadata`

### ISSUE THREAD

**Issue by Kreijstal** [Anadian/executable-metadata#1]
Need to install the following packages:
  executable-metadata
Ok to proceed? (y) y
The system cannot find the path specified.

**Comment by Kreijstal** [comment]
no matter what you do, it cannot file the system path specified

**Comment by Kreijstal** [comment]
This is on windows 10 using node 17

**Comment by Anadian** [comment]
Yes, I've been meaning to look into this; now that I've got a free moment, I will.

**Comment by Anadian** [comment]
Okay, please try out the latest version (`v0.1.3`) and see if it has fixed the issue. Let me know what you find.

**Comment by Anadian** [comment]
Oh and make sure you're doing a full reinstall from NPM. Thank you.

**Comment by Kreijstal** [comment]
Yes, it works now! I would like to point out, that when no command parameters are given it "crashes". That is however a separate issue :)

**Comment by Anadian** [comment]
Thank you again for reminding me of this. Also I just fixed the misplaced parametre check that caused the aforementioned soft "crash." That combined with having fixed the Windows install issues: I've bumped the version to v0.2.0.
